name: "Security Scan"
on: [push, pull_request]
permissions: read-all
jobs:
  gosec:
    name: Gosec Security Scanner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get GO_VERSION
        id: get-go-version
        run: |
          set -eou pipefail
          go_version=$(cat GO_VERSION | tr -d '\n')
          echo "GO_VERSION=$go_version" >> $GITHUB_OUTPUT

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ steps.get-go-version.outputs.GO_VERSION }}

      - name: Run gosec on Windows files
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          find . -name '*windows*.go' -not -path '*/vendor/*' -not -name '*_test.go' | xargs gosec -include=G204
