name: "Security Scan"
on: [push, pull_request]
permissions: read-all
jobs:
  semgrep:
    name: Semgrep Security Scanner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run semgrep on new changes
        env:
          SEMGREP_RULES: .github/semgrep/rules.yml
        run: |
          pip install semgrep --quiet
          semgrep --config $SEMGREP_RULES --baseline-commit $(git merge-base HEAD origin/master)
